---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "python-course-app-lesson13"
  name: "python-course-app-lesson13-service"
spec:
  type: ClusterIP
  selector:
    app: "python-course-app-lesson13"
  ports:
  - name: python-course-app-lesson13-service
    port: 8080
    protocol: TCP
    targetPort: 8080

  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600  
...

